# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post2',
            old_name='title',
            new_name='country_name',
        ),
        migrations.RemoveField(
            model_name='post2',
            name='text',
        ),
    ]
